language: cpp
sudo: required
dist: xenial

git:
  depth: 3

env:
  global:
    - COMPILE_ASIO=0

matrix:
  include:
    # linux with MXE
    - env: TARGET="windows64"
      os: linux
      dist: trusty
    # linux with gcc 8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  - if [[ "$TARGET" == "windows64" ]]; then ci/mxe-requirements.sh; fi
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi

install:
  - ci/install-deps.sh

before_script:
  - ci/build-deps.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/qt/lib/pkgconfig:/usr/local/lib/pkgconfig; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/qt/bin:$PATH"; fi
  - autoreconf -vfi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure --prefix='/usr'; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make && sudo make install; fi

after_failure:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ls -alhv /usr/bin/ |grep -E "(clang|gcc|g\+\+)"; fi
  - if [[ -f config.log ]]; then cat config.log; fi

branches:
  only:
    - master
    - travis-integration
    - ssr-windows
    - mxe
    - beta

notifications:
  email: false
